/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import controller.UserController;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import modelos.UserModel;

/**
 *
 * @author thepr
 */
public class jfrAccount extends javax.swing.JFrame {

    /**
     * Creates new form jfrAccount
     */
    private static String users;
    public jfrAccount(String user) {
        initComponents();
        Account(user);
        users = user;
    }

    public void Account(String user){
        int word= 0;
        String wordreplace = "";
        UserController uc = new UserController();
        UserModel usm = new UserModel(0, null, null, null);
        usm = uc.searchuser(user);
        jlblEmail.setText(usm.getEmail());
        jlblUser.setText(usm.getUser());
        word = usm.getPassword().length();
        for(int i = 0; i < word; i++){
            wordreplace = wordreplace + "*"; 
        }
        jlblPassword.setText(usm.getPassword().replace(usm.getPassword(), wordreplace));
    }
    
    private jfrAccount() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jlbNameUs = new javax.swing.JLabel();
        jlblEmailUser = new javax.swing.JLabel();
        jlblPass = new javax.swing.JLabel();
        jlblPassword = new javax.swing.JLabel();
        jlblUser = new javax.swing.JLabel();
        jlblEmail = new javax.swing.JLabel();
        jbtnShowPass = new javax.swing.JButton();
        jbtnBackAccount1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jbtnBack.setText("VOLVER");
        jbtnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnBackMouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbNameUs.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlbNameUs.setText("Nombre de usuario: ");
        jPanel1.add(jlbNameUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 36, -1, -1));

        jlblEmailUser.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlblEmailUser.setText("Correo del usuario: ");
        jPanel1.add(jlblEmailUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 83, -1, -1));

        jlblPass.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlblPass.setText("Contraseña del usuario:");
        jPanel1.add(jlblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jlblPassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jlblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 130, -1, -1));

        jlblUser.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jlblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 36, -1, -1));

        jlblEmail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jlblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 83, -1, -1));

        jbtnShowPass.setBackground(new java.awt.Color(0, 0, 0));
        jbtnShowPass.setForeground(new java.awt.Color(255, 255, 255));
        jbtnShowPass.setText("MOSTRAR");
        jbtnShowPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnShowPassMouseClicked(evt);
            }
        });
        jPanel1.add(jbtnShowPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 120, 50));

        jbtnBackAccount1.setBackground(new java.awt.Color(0, 0, 0));
        jbtnBackAccount1.setForeground(new java.awt.Color(255, 255, 255));
        jbtnBackAccount1.setText("VOLVER");
        jbtnBackAccount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackAccount1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnBackAccount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 120, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo-azul-galaxia_125540-99.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 600, 280));

        jMenu1.setText("Perfil");

        jMenuItem1.setText("Cerrar Sesión");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnBackMouseClicked
        this.dispose();
    }//GEN-LAST:event_jbtnBackMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jfrLogIn login = new jfrLogIn();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
   
    
    private void jbtnShowPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnShowPassMouseClicked
        if(jbtnShowPass.getText().equals("MOSTRAR")){
            jbtnShowPass.setText("OCULTAR");
            UserController uc = new UserController();
            UserModel usm = new UserModel(0, null, null, null);
            usm = uc.searchuser(users);
            jlblPassword.setText(usm.getPassword());
        }else{
            jbtnShowPass.setText("MOSTRAR");
            int word = 0;
            String wordreplace = "";
            UserController uc = new UserController();
            UserModel usm = new UserModel(0, null, null, null);
            usm = uc.searchuser(users);
            word = usm.getPassword().length();
            for(int i = 0; i < word; i++){
                wordreplace = wordreplace + "*"; 
            }
            jlblPassword.setText(usm.getPassword().replace(usm.getPassword(), wordreplace));
        }
    }//GEN-LAST:event_jbtnShowPassMouseClicked

    private void jbtnBackAccount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackAccount1ActionPerformed
        jfrLogged logged = new jfrLogged(users);
        logged.setLocationRelativeTo(null);
        logged.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnBackAccount1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnBackAccount1;
    private javax.swing.JButton jbtnShowPass;
    private javax.swing.JLabel jlbNameUs;
    private javax.swing.JLabel jlblEmail;
    private javax.swing.JLabel jlblEmailUser;
    private javax.swing.JLabel jlblPass;
    private javax.swing.JLabel jlblPassword;
    private javax.swing.JLabel jlblUser;
    // End of variables declaration//GEN-END:variables
}
