/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import controller.UserController;
import javax.swing.JOptionPane;

/**
 *
 * @author thepr
 */
public class jfrLogIn extends javax.swing.JFrame {

    /**
     * Creates new form jfrLog
     */
    public jfrLogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnDispose = new javax.swing.JButton();
        jbtnRegister = new javax.swing.JButton();
        jbtnLogIn = new javax.swing.JButton();
        jtxtlblPassword = new javax.swing.JPasswordField();
        jlblPasswd = new javax.swing.JLabel();
        jlblLogin = new javax.swing.JLabel();
        jtxtlblUser = new javax.swing.JTextField();
        jlblTextLog = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnDispose.setBackground(new java.awt.Color(0, 0, 0));
        jbtnDispose.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnDispose.setForeground(new java.awt.Color(255, 255, 255));
        jbtnDispose.setText("Cerrar");
        jbtnDispose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnDisposeMouseClicked(evt);
            }
        });
        jPanel1.add(jbtnDispose, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 120, 50));

        jbtnRegister.setBackground(new java.awt.Color(0, 0, 0));
        jbtnRegister.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnRegister.setForeground(new java.awt.Color(255, 255, 255));
        jbtnRegister.setText("Registrarse");
        jbtnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnRegisterMouseClicked(evt);
            }
        });
        jPanel1.add(jbtnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 120, 50));

        jbtnLogIn.setBackground(new java.awt.Color(0, 0, 0));
        jbtnLogIn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnLogIn.setForeground(new java.awt.Color(255, 255, 255));
        jbtnLogIn.setText("Iniciar Sesión");
        jbtnLogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnLogInMouseClicked(evt);
            }
        });
        jPanel1.add(jbtnLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 120, 50));

        jtxtlblPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(jtxtlblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 210, -1));

        jlblPasswd.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlblPasswd.setText("Contraseña:");
        jPanel1.add(jlblPasswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 140, 40));

        jlblLogin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlblLogin.setText("Usuario:");
        jPanel1.add(jlblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 100, 40));

        jtxtlblUser.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtxtlblUser.setToolTipText("");
        jPanel1.add(jtxtlblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 210, -1));

        jlblTextLog.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlblTextLog.setText("Iniciar Sesión");
        jPanel1.add(jlblTextLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 210, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/21c23fd79c981df5afa862abf54c00a4.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 170, 120));

        jlblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo-azul-galaxia_125540-99.jpg"))); // NOI18N
        jPanel1.add(jlblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -100, 660, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDisposeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnDisposeMouseClicked
        System.exit(0);
        this.dispose();
    }//GEN-LAST:event_jbtnDisposeMouseClicked

    private void jbtnRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnRegisterMouseClicked
        jfrSignIn signin = new jfrSignIn();
        signin.setLocationRelativeTo(null);
        signin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnRegisterMouseClicked

    private void jbtnLogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnLogInMouseClicked
        String user = jtxtlblUser.getText();
        String password = jtxtlblPassword.getText();
        UserController usc = new UserController();
        if(usc.LogIn(user, password) == true){
            System.out.println("SESIÓN INICIADA");
            jfrLogged logged = new jfrLogged(user);
            logged.setLocationRelativeTo(null);
            logged.setVisible(true);
            this.dispose();
        }else{
            System.out.println("ERROR SESIÓN NO INICIADA\nCORREO O CONTRASEÑA NO EXISTE");
            JOptionPane.showMessageDialog(null, "ERROR SESIÓN NO INICIADA\nCORREO O CONTRASEÑA NO EXISTE", "ERROR NO INICIA SESION", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnLogInMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jfrLogIn login = new jfrLogIn();
                login.setLocationRelativeTo(null);
                login.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnDispose;
    private javax.swing.JButton jbtnLogIn;
    private javax.swing.JButton jbtnRegister;
    private javax.swing.JLabel jlblBackground;
    private javax.swing.JLabel jlblLogin;
    private javax.swing.JLabel jlblPasswd;
    private javax.swing.JLabel jlblTextLog;
    private javax.swing.JPasswordField jtxtlblPassword;
    private javax.swing.JTextField jtxtlblUser;
    // End of variables declaration//GEN-END:variables
}
