/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import controller.UserController;
import java.awt.Font;
import javax.swing.JLabel;
import modelos.UserModel;

/**
 *
 * @author thepr
 */
public class jfrLogged extends javax.swing.JFrame {

    /**
     * Creates new form jfrLogged
     */
    private JLabel welcome;
    private static String users;
    
    public jfrLogged(String user) {
        initComponents();
        welcome(user);
        users = user;
    }

    private jfrLogged() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    public void welcome(String user){
        JLabel welcome = new JLabel();
        welcome.setText("Welcome " + user);
        welcome.setFont(new Font("Tahoma", Font.PLAIN, 36));;
        welcome.setVerticalAlignment((int) CENTER_ALIGNMENT);
        welcome.setBounds(150, 10, 400, 70);
        welcome.setVisible(true);
        add(welcome, JLabel.CENTER);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbBackground = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAccount = new javax.swing.JMenu();
        jmitShowAccount = new javax.swing.JMenuItem();
        jmitLogOut = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo-azul-galaxia_125540-99.jpg"))); // NOI18N
        jPanel1.add(jlbBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 420));

        jmAccount.setText("Perfil");

        jmitShowAccount.setText("Ver Perfil");
        jmitShowAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitShowAccountActionPerformed(evt);
            }
        });
        jmAccount.add(jmitShowAccount);

        jmitLogOut.setText("Cerrar Sesión");
        jmitLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitLogOutActionPerformed(evt);
            }
        });
        jmAccount.add(jmitLogOut);

        jMenuBar1.add(jmAccount);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmitLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitLogOutActionPerformed
        jfrLogIn m = new jfrLogIn();
        m.setLocationRelativeTo(null);
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmitLogOutActionPerformed

    private void jmitShowAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitShowAccountActionPerformed
        UserController usc = new UserController();
        UserModel usm = usc.searchuser(users);
        jfrAccount account = new jfrAccount(usm.getUser());
        account.setLocationRelativeTo(null);
        account.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmitShowAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrLogged.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrLogged.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrLogged.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrLogged.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jfrLogged looged = new jfrLogged();
                looged.setLocationRelativeTo(null);
                looged.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbBackground;
    private javax.swing.JMenu jmAccount;
    private javax.swing.JMenuItem jmitLogOut;
    private javax.swing.JMenuItem jmitShowAccount;
    // End of variables declaration//GEN-END:variables
}
