/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import controller.UserController;
import javax.swing.JOptionPane;

/**
 *
 * @author thepr
 */
public class jfrSignIn extends javax.swing.JFrame {

    /**
     * Creates new form jfrSignIn
     */
    public jfrSignIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblSignIn = new javax.swing.JLabel();
        jlblUser = new javax.swing.JLabel();
        jtxtUser = new javax.swing.JTextField();
        jlblEmail = new javax.swing.JLabel();
        jtxtfEmail = new javax.swing.JTextField();
        jtxtfPassword = new javax.swing.JTextField();
        jlblPassword = new javax.swing.JLabel();
        jbtnSignIn1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jbtnDispose = new javax.swing.JButton();
        jlblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblSignIn.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jlblSignIn.setText("REGISTRARSE");
        jPanel1.add(jlblSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jlblUser.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlblUser.setText("Nombre Usuario:");
        jPanel1.add(jlblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));
        jPanel1.add(jtxtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 192, 36));

        jlblEmail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlblEmail.setText("Correo electrónico:");
        jPanel1.add(jlblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
        jPanel1.add(jtxtfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 192, 36));
        jPanel1.add(jtxtfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 192, 36));

        jlblPassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlblPassword.setText("Contraseña:");
        jPanel1.add(jlblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        jbtnSignIn1.setBackground(new java.awt.Color(0, 0, 0));
        jbtnSignIn1.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSignIn1.setText("REGISTRARSE");
        jbtnSignIn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnSignIn1MouseClicked(evt);
            }
        });
        jPanel1.add(jbtnSignIn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 120, 50));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Volver");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 120, 50));

        jbtnDispose.setBackground(new java.awt.Color(0, 0, 0));
        jbtnDispose.setForeground(new java.awt.Color(255, 255, 255));
        jbtnDispose.setText("CERRAR");
        jbtnDispose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnDisposeMouseClicked(evt);
            }
        });
        jPanel1.add(jbtnDispose, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 120, 50));

        jlblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo-azul-galaxia_125540-99.jpg"))); // NOI18N
        jPanel1.add(jlblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSignIn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSignIn1MouseClicked
        String email = jtxtfEmail.getText();
        String user = jtxtUser.getText();
        String pass = jtxtfPassword.getText();
        
        if(!email.isEmpty() && !user.isEmpty() && !pass.isEmpty()){
           if(email.contains("@gmail.") || email.contains("@outlook.") || email.contains("@yahoo.") || email.contains("@hotmail.")){
                UserController usc = new UserController();
                
                if(!usc.accountExist(email, user)){
                    if(usc.SignIn(email, user, pass) == true){
                        JOptionPane.showMessageDialog(null, "USUARIO REGISTRADO", "REGISRO", JOptionPane.INFORMATION_MESSAGE);
                        jfrLogIn m = new jfrLogIn();
                        m.setLocationRelativeTo(null);
                        m.setVisible(true);
                        this.dispose();
                    }else{
                        JOptionPane.showMessageDialog(null, "ERROR NO SE CREO EL USUARIO", "ERROR USUARIO NO CREADO", JOptionPane.ERROR_MESSAGE);
                   }
                }else{
                    JOptionPane.showMessageDialog(null, "EL USUARIO YA EXISTE", "USUARIO EXISTE", JOptionPane.WARNING_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null, "TIENES QUE ESCRIBIR UN CORREO ELECTRONICO", "CORREO NO EXISTENTE", JOptionPane.WARNING_MESSAGE);

           }
        }else{
            JOptionPane.showMessageDialog(null, "TIENES QUE RELLENAR EL CORREO, USUARIO Y CONTRASEÑA", "REGISTRO VACIO", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jbtnSignIn1MouseClicked

    private void jbtnDisposeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnDisposeMouseClicked
        System.exit(0);
        this.dispose();
    }//GEN-LAST:event_jbtnDisposeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrSignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnDispose;
    private javax.swing.JButton jbtnSignIn1;
    private javax.swing.JLabel jlblBackground;
    private javax.swing.JLabel jlblEmail;
    private javax.swing.JLabel jlblPassword;
    private javax.swing.JLabel jlblSignIn;
    private javax.swing.JLabel jlblUser;
    private javax.swing.JTextField jtxtUser;
    private javax.swing.JTextField jtxtfEmail;
    private javax.swing.JTextField jtxtfPassword;
    // End of variables declaration//GEN-END:variables
}
